spring:
  datasource:
    url: ${AWS_DB_URL}
    username: ${AWS_DB_USER}
    password: ${AWS_DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

kakao:
  client_id: ${KAKAO_CLIENT_ID}
  redirect_uri: ${KAKAO_REDIRECT_URI}
  client_secret: ${KAKAO_CLIENT_SECRET}
  token_uri: ${KAKAO_TOKEN_URI}
  user_info_uri: ${KAKAO_USER_INFO_URI}
  unlink_callback_uri: ${KAKAO_UNLINK_CALLBACK_URI}

cloud:
  aws:
    s3:
      bucket: yahobucket
      path:
        mvp : mvps
        profileImg : profileImg
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}